### ISSUE TITLE
Docker run

### ISSUE THREAD

**Issue by serhatbolsu** [sorccu/docker-adb#4]
Hello,
Thank you for this repo, it is greatly helping me. 
Here is the thing I would like to talk with you:

1- Ones I start docker with pattern -1 or -2, docker adb also appear in host machine processes. `ps -ef | grep adb`. Also when I run `adb devices` it normally run just as adb running on host. Is not this abnormal since adb process is actually running inside docker image.

2- Normally `docker run` is to **start a container**. It seems you are doing multiple `docker run` in one of the patters you explain. do you think these actually should be `docker exec`.
ex. pattern 2 

        docker run -d --privileged --net host -v /dev/bus/usb:/dev/bus/usb --name adbd sorccu/adb
        docker exec adbd adb devices

Thank you

**Comment by sorccu** [comment]
This image is meant to be run on a dedicated server where you have nothing but devices plugged in. Therefore taking over the 5037 port is not an issue, but a desired feature.

There are multiple `docker run` commands to demonstrate how the image might be used. But yes, `docker exec` is also a possibility if you prefer it. Note that `docker exec` did not exist when this image was originally created.

You don't have to limit yourself to the patterns mentioned in the README. If you can find a way to use it that works for you, go ahead.
