### ISSUE TITLE
adbkey and adbkey.pub

### ISSUE THREAD

**Issue by alexislg2** [sorccu/docker-adb#5]
There's a mistake in both the Dockerfile and the documentation: The path of the adbkeys is `/root/.android/` not `/.android/`

Do you want a PR?

**Comment by sorccu** [comment]
That was not the case before, however the behavior may have changed. Could you verify your findings by installing adb yourself, running once, and then checking where it placed the files?

**Comment by alexislg2** [comment]
Well I spent last hour trying to figure out why my adbkeys where not working. and then I found that there is another directory /root/.android/ that contains other adbkeys. After mounting my keys into that directory it worked perfectly

But that makes sense. Those keys should be stored in the ~/.android directory so that corresponds to /root/.android

**Comment by sorccu** [comment]
It does make sense, however that's not how it worked before, so I'm just wondering where and when it changed. I can't spend much time on this, so if you can verify that your findings are correct and submit a PR with a Dockerfile that builds, that would be great.

**Comment by alexislg2** [comment]
OK I will do that. I did verify my findings

**Comment by sorccu** [comment]
(As a side note I feel that the image is too large, mainly because of the difficulty of downloading the ADB binary. It would be great if someone could take a look into it. I probably can't do it for at least the next month or so.)

**Comment by alexislg2** [comment]
can't we just apt-get install android-tools-adb android-tools-fastboot ?
But maybel that will result in same image size.
Other solution would be to build from source but again that might give a big image in the end

**Comment by sorccu** [comment]
No, those are horribly out of date. Presumably precisely because they're
annoying to build by themselves.

**Comment by sorccu** [comment]
Sorry, I got a motivation boost from your feedback, had a pretty good idea on how to do the download more efficiently, and just went ahead with a full redesign. I fixed this issue during the redesign.
